### ISSUE TITLE
🚨 IMPORTANT 🚨  This project isn't maintained anymore, please use the fork Tanton instead

### ISSUE THREAD

**Issue by chase-manning** [pleco-rs/Pleco#140]
This repo is no longer maintained, and hasn't had any new commits in two and half years.

It has been forked and redeployed with active maintenance, please use this instead:
- [Tandon Repo](https://github.com/chase-manning/tanton)
- [Tandon Crate (Pleco Crate)](https://crates.io/crates/tanton/)
- [Tandon Engine Crate (Pleco Engine Crate)](https://crates.io/crates/tanton_engine)

**Comment by LinusCDE** [comment]
Just for the sake of organizing, these PRs seem to be results of this issue and address mostly the same point. So discussion or why this happened is probably best discussed here.

 - https://github.com/dfinity/cdk-rs/pull/345
 - https://github.com/Wandalen/game_chess/pull/286
 - https://github.com/lucasradaelli/blindfold-chess/pull/1
 - https://github.com/sdbondi/p2p-chess/pull/15
 - https://github.com/LinusCDE/chessmarkable/pull/21
