### ISSUE TITLE
Midgame centipawn conversion is off

### ISSUE THREAD

**Issue by nicholasfagan** [pleco-rs/Pleco#149]
There's likely a typo in the conversion of values to centipawns.
Line 76 has `self.mg() / PAWN_EG`, where it should likely be `self.mg() / PAWN_MG`.

https://github.com/pleco-rs/Pleco/blob/26d6fbb44d4166081abde0536f2958db7fab4e3f/pleco/src/core/score.rs#L74-L79

**Comment by chase-manning** [comment]
@nicholasfagan  Thanks so much for raising this issue! Has just been fixed in PR: #150
