### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by brianch** [pleco-rs/Pleco#151]
Hello,

Since pleco_engine is a re-write of Stockfish, shouldn't it use the GPL license too? The GPL and MIT aren't compatible.

Edit: Aren't compatible in the GPL -> MIT direction (since the later is more permissive, doesn't have copyleft)

**Comment by chase-manning** [comment]
@brianch Yes that sounds reasonable to me 😄 

Feel free to open a PR with this change, or I can raise one at some later time 👍🏻
